
let building = { 
	"YiXin canteen": "益新食堂", 
	"ErMei canteen": "尔美餐厅", 
	"WuXin canteen": "吾馨", 
	"SanMing canteen":"山明食堂",
	"ShuiXiu canteen":"水秀餐厅",
	"Shuixiu educational store":"水秀教超",
	"South-district dormitory":"南区宿舍",
	"Logistics basic erection building":"后勤基建大楼",
	"New century dormitory":"新世纪大学村",
	"West gate":"西门",
	"West basketball court":"西门篮球场",
	"West educational store":"西门教育超市",
	"Cainiao station":"菜鸟驿站",
	"Shangda bathroom":"上大浴室",
	"Yixin store":"益新教育超市",
	"S2":"S2",
	"S1":"S1",
	"T1":"T1",
	"T2":"T2",
	"Tennis Centre":"网球中心",
	"Indoor Tennis Stadium":"网球馆",
	"Subway station":"地铁站",
	"school infirmary": "校医院",
	"PanXi Bookstore": "畔溪书店",
	"LeHu building":"乐乎新楼",
	"International SCIE":"国际交流学院",
	"Library lecture hall":"图报厅",
	"Library":"图书馆",
	"Building One":"一号楼",
	"Building Two":"二号楼",
	"Building Three":"三号楼",
	"Building Four":"四号楼",
	"Building Five":"五号楼",
	"K-soccer field":"K区篮球场",
	"South district basketball court":"南区篮球场",
	"Panchi":"泮池",
	"Academy of fine arts":"美术学院",
	"The southeast gate":"东南门",
	"School of Economics and Management":"经管大楼",
	"Qian weichang Library":"钱伟长图书馆",
	"School of mechanical automation":"机自楼",
	"Xiangying Building":"翔英大楼",
	"Yong fu nunnery":"永福庵",
	"School of computer science":"计算机学院",
	"Institute of materials":"材料楼",
	"The playground":"运动场",
	"The natatorium":"游泳馆",
	"Training venue":"训练馆",
	"The gym":"体育馆",
	"College of music":"音乐学院",
	"Wei long floor":"伟长楼",
	"Football field":"足球场",
	"The administration building":"行政楼",
	"A Building":"A教学楼",
	"AJ Building":"AJ教学楼",
	"B Building":"B楼",
	"BJ Building":"BJ楼",
	"C Building":"C楼",
	"CJ Building":"CJ楼",
	"D Building":"D楼",
	"DJ Building":"DJ楼",
	"J Building":"J楼",
	"G Building":"G教学楼",
	"GJ Building":"GJ教学楼",
	"FJ Building":"FJ教学楼",
	"F Building":"F教学楼",
	"EJ Building":"EJ教学楼",
	"E Building":"纳米化学与生物研究所",
	"Student service centre":"学生服务中心",
	"Celebrity square":"名人广场",
	"D-educational store":"D楼教超",
}